dist: bionic   # use the most recent release
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y systemd-container
install:
  - pip install pylint
jobs:
  include:
    - name: pylint
      script: pylint osbuild assemblers/* stages/*
    - name: pipeline-noop
      script: sudo env "PATH=$PATH" python3 -m osbuild --libdir . --output . samples/noop.json
    - name: pipeline-yum
      script: sudo env "PATH=$PATH" python3 -m osbuild --libdir . --output . samples/yum.json
